### ISSUE TITLE
appwrite/code/docker-compose.yml

### ISSUE THREAD

**Issue by biznizai** [easypanel-io/compose#3]
Please can we update the version to latest? Thanks in advance

**Comment by altrsadmin** [comment]
Following up! We also have this pending issue. As a suggestion, and complementing the colleague’s request, perhaps permanently set an ENV variable to determine the tag

**Comment by altrsadmin** [comment]
@biznizai 
Hello friend, I am not a programmer. I forked and set the TAG variable to "latest" in the ENV and made the changes in the YAML.It seems to have worked; you can copy it from the link below.P.S. I lost all the data. It seems that when updating/installing, it didn't automatically create persistent volumes, and honestly, I still don't know how to solve this.

https://github.com/altrsadmin/compose

**Comment by biznizai** [comment]
Please try going back to 1.5.7. it's the latest possible according to https://appwrite.io/install/compose and it seems like they need to update they're docker I did ask in an issue but it seems it disapeared into the ether
